// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devops-super/internal/dao/internal"
)

// internalCiEnvDao is internal type for wrapping internal DAO implements.
type internalCiEnvDao = *internal.CiEnvDao

// ciEnvDao is the data access object for table ci_env.
// You can define custom methods on it to extend its functionality as you wish.
type ciEnvDao struct {
	internalCiEnvDao
}

var (
	// CiEnv is globally public accessible object for table ci_env operations.
	CiEnv = ciEnvDao{
		internal.NewCiEnvDao(),
	}
)

// Fill with you ideas below.
