// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devops-super/internal/dao/internal"
)

// internalCiPipelineRunDao is internal type for wrapping internal DAO implements.
type internalCiPipelineRunDao = *internal.CiPipelineRunDao

// ciPipelineRunDao is the data access object for table ci_pipeline_run.
// You can define custom methods on it to extend its functionality as you wish.
type ciPipelineRunDao struct {
	internalCiPipelineRunDao
}

var (
	// CiPipelineRun is globally public accessible object for table ci_pipeline_run operations.
	CiPipelineRun = ciPipelineRunDao{
		internal.NewCiPipelineRunDao(),
	}
)

// Fill with you ideas below.
