// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devops-super/internal/dao/internal"
)

// internalCiPipelineDao is internal type for wrapping internal DAO implements.
type internalCiPipelineDao = *internal.CiPipelineDao

// ciPipelineDao is the data access object for table ci_pipeline.
// You can define custom methods on it to extend its functionality as you wish.
type ciPipelineDao struct {
	internalCiPipelineDao
}

var (
	// CiPipeline is globally public accessible object for table ci_pipeline operations.
	CiPipeline = ciPipelineDao{
		internal.NewCiPipelineDao(),
	}
)

// Fill with you ideas below.
