// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devops-super/internal/dao/internal"
)

// internalHostGroupDao is internal type for wrapping internal DAO implements.
type internalHostGroupDao = *internal.HostGroupDao

// hostGroupDao is the data access object for table host_group.
// You can define custom methods on it to extend its functionality as you wish.
type hostGroupDao struct {
	internalHostGroupDao
}

var (
	// HostGroup is globally public accessible object for table host_group operations.
	HostGroup = hostGroupDao{
		internal.NewHostGroupDao(),
	}
)

// Fill with you ideas below.
