// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devops-super/internal/dao/internal"
)

// internalHostTerminalSessionDao is internal type for wrapping internal DAO implements.
type internalHostTerminalSessionDao = *internal.HostTerminalSessionDao

// hostTerminalSessionDao is the data access object for table host_terminal_session.
// You can define custom methods on it to extend its functionality as you wish.
type hostTerminalSessionDao struct {
	internalHostTerminalSessionDao
}

var (
	// HostTerminalSession is globally public accessible object for table host_terminal_session operations.
	HostTerminalSession = hostTerminalSessionDao{
		internal.NewHostTerminalSessionDao(),
	}
)

// Fill with you ideas below.
