// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devops-super/internal/dao/internal"
)

// internalKubernetesConfigDao is internal type for wrapping internal DAO implements.
type internalKubernetesConfigDao = *internal.KubernetesConfigDao

// kubernetesConfigDao is the data access object for table kubernetes_config.
// You can define custom methods on it to extend its functionality as you wish.
type kubernetesConfigDao struct {
	internalKubernetesConfigDao
}

var (
	// KubernetesConfig is globally public accessible object for table kubernetes_config operations.
	KubernetesConfig = kubernetesConfigDao{
		internal.NewKubernetesConfigDao(),
	}
)

// Fill with you ideas below.
