// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devops-super/internal/dao/internal"
)

// internalSecretDao is internal type for wrapping internal DAO implements.
type internalSecretDao = *internal.SecretDao

// secretDao is the data access object for table secret.
// You can define custom methods on it to extend its functionality as you wish.
type secretDao struct {
	internalSecretDao
}

var (
	// Secret is globally public accessible object for table secret operations.
	Secret = secretDao{
		internal.NewSecretDao(),
	}
)

// Fill with you ideas below.
